defmodule TheSpread.ExampleRequest do
  # Sport: ncaa_basketball
  # Date: 2017-02-10
  def massey_row1 do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus1 tr0"}, {"data-idx", "3"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531525"}], ["Fri 02.10"]},
     {"div", [{"class", "detail red"}],
      [{"a",
        [{"href",
          "http://www.google.com/cse?cx=partner-pub-0379030414683754:9954400133&ie=UTF-8&q=Dayton Flyers 75 Rhode Island Rams 74 box score&sa=Search&ref=#gsc.tab=0&gsc.q=Dayton Flyers 75 Rhode Island Rams 74 box score&gsc.page=1"}],
        ["FINAL"]}]}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=2085"}], ["Dayton"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=6516"}], ["@ Rhode Island"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 32 (19-5)", {"div", [{"class", "undefined"}], ["# 56 (16-8)"]}]},
   {"td", [{"class", "fscore greybg cWin"}],
    ["75", {"div", [{"class", "undefined white"}], ["74"]}]},
   {"td", [{"class", "fpred white"}],
    ["67", {"div", [{"class", "undefined cWin"}], ["68"]}]},
   {"td", [{"class", "fpred white"}],
    ["48 %", {"div", [{"class", "undefined cWin"}], ["52 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltred visHidden"}], ["4.0"]},
     {"div", [{"class", " ltgreen"}], ["-1.5"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["135.5", {"div", [{"class", "ltred visHidden"}], ["138.5"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end

  def massey_row2 do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus1 tr1"}, {"data-idx", "4"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531526"}], ["Fri 02.10"]},
     {"div", [{"class", "detail red"}],
      [{"a",
        [{"href",
          "http://www.google.com/cse?cx=partner-pub-0379030414683754:9954400133&ie=UTF-8&q=Oakland Golden Grizzlies 89 Detroit Titans 80 box score&sa=Search&ref=#gsc.tab=0&gsc.q=Oakland Golden Grizzlies 89 Detroit Titans 80 box score&gsc.page=1"}],
        ["FINAL"]}]}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=5783"}], ["Oakland"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=2176"}], ["@ Detroit"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 117 (19-7)", {"div", [{"class", "undefined"}], ["# 295 (6-19)"]}]},
   {"td", [{"class", "fscore greybg cWin"}],
    ["89", {"div", [{"class", "undefined white"}], ["80"]}]},
   {"td", [{"class", "fpred cWin"}],
    ["85", {"div", [{"class", "undefined white"}], ["76"]}]},
   {"td", [{"class", "fpred cWin"}],
    ["79 %", {"div", [{"class", "undefined white"}], ["21 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltgreen"}], ["-8.5"]},
     {"div", [{"class", "ltred visHidden"}], ["7.5"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["161.5", {"div", [{"class", "ltred visHidden"}], ["163.5"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end

  def massey_row3 do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus1 tr0"}, {"data-idx", "2"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531528"}], ["Fri 02.10"]},
     {"div", [{"class", "detail red"}],
      [{"a",
        [{"href",
          "http://www.google.com/cse?cx=partner-pub-0379030414683754:9954400133&ie=UTF-8&q=Dartmouth Big Green 64 Yale Bulldogs 73 box score&sa=Search&ref=#gsc.tab=0&gsc.q=Dartmouth Big Green 64 Yale Bulldogs 73 box score&gsc.page=1"}],
        ["FINAL"]}]}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=2052"}], ["Dartmouth"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=9177"}], ["@ Yale"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 318 (4-16)", {"div", [{"class", "undefined"}], ["# 105 (14-6)"]}]},
   {"td", [{"class", "fscore greybg white"}],
    ["64", {"div", [{"class", "undefined cWin"}], ["73"]}]},
   {"td", [{"class", "fpred white"}],
    ["61", {"div", [{"class", "undefined cWin"}], ["78"]}]},
   {"td", [{"class", "fpred white"}],
    ["6 %", {"div", [{"class", "undefined cWin"}], ["94 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltred visHidden"}], ["15.0"]},
     {"div", [{"class", " ltgreen"}], ["-16.5"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["140.5", {"div", [{"class", "ltred visHidden"}], ["138.5"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end

  def massey_row4 do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus1 tr1"}, {"data-idx", "1"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531524"}], ["Fri 02.10"]},
     {"div", [{"class", "detail red"}],
      [{"a",
        [{"href",
          "http://www.google.com/cse?cx=partner-pub-0379030414683754:9954400133&ie=UTF-8&q=Cornell Big Red 60 Princeton Tigers 69 box score&sa=Search&ref=#gsc.tab=0&gsc.q=Cornell Big Red 60 Princeton Tigers 69 box score&gsc.page=1"}],
        ["FINAL"]}]}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=1910"}], ["Cornell"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=6339"}], ["@ Princeton"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 291 (6-16)", {"div", [{"class", "undefined"}], ["# 86 (14-6)"]}]},
   {"td", [{"class", "fscore greybg white"}],
    ["60", {"div", [{"class", "undefined cWin"}], ["69"]}]},
   {"td", [{"class", "fpred white"}],
    ["63", {"div", [{"class", "undefined cWin"}], ["77"]}]},
   {"td", [{"class", "fpred white"}],
    ["9 %", {"div", [{"class", "undefined cWin"}], ["91 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltred visHidden"}], ["16.0"]},
     {"div", [{"class", " ltgreen"}], ["-14.5"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["139.5", {"div", [{"class", "ltred visHidden"}], ["140.0"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end

  def massey_row_game_not_over do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus2 tr0"}, {"data-idx", "13"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531676"}], ["Mon 02.13"]},
     {"div", [{"class", "detail"}], []}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=2899"}], ["Ga Southern"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=275"}], ["@ Appalachian St"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 120 (16-8)", {"div", [{"class", "undefined"}], ["# 293 (6-16)"]}]},
   {"td", [{"class", "fscore greybg white"}],
    ["0", {"div", [{"class", "undefined white"}], ["0"]}]},
   {"td", [{"class", "fpred cWin"}],
    ["78", {"div", [{"class", "undefined white"}], ["74"]}]},
   {"td", [{"class", "fpred cWin"}],
    ["65 %", {"div", [{"class", "undefined white"}], ["35 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltgreen"}], ["-4.5"]},
     {"div", [{"class", "ltred visHidden"}], ["---"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["153.5", {"div", [{"class", "ltred visHidden"}], ["---"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end

  def wunder_row1 do
    [{"tr", [{"class", ""}],
   [{"td", [], ["\n                      6:30pm                  "]},
    {"td", [], ["887"]},
    {"td", [{"style", "white-space:nowrap"}], ["Ohio Bobcats"]},
    {"td", [], ["465 "]},
    {"td", [], ["\n                        49%          "]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress grey wd_progress"}],
       [{"div",
         [{"style", "width:  49%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}, {"td", [], ["50 "]},
    {"td", [], ["\n            49%          "]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress grey wd_progress"}],
       [{"div",
         [{"style", "width:  49%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}, {"td", [], ["O 338 "]},
    {"td", [], [{"font", [{"color", "green"}], ["67%"]}]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress wd_progress"}],
       [{"div",
         [{"style", "width:  67%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}]},
  {"tr", [{"class", ""}],
   [{"td", [],
     [{"a",
       [{"href", "/consensus/viewScoreOdds/event_id/429862.html?width=610"},
        {"name",
         "Ohio Bobcats vs. Ball State Cardinals - Friday February 10, 2017 6:30 pm"},
        {"class", "jTip hidden-xs"}, {"id", "429862"}], ["score »"]},
      {"a",
       [{"href", "/consensus/viewScoreOdds/event_id/429862.html"},
        {"name",
         "Ohio Bobcats vs. Ball State Cardinals - Friday February 10, 2017 6:30 pm"},
        {"class", "visible-xs"}, {"id", "429862"}], ["score »"]}]},
    {"td", [], ["888"]},
    {"td", [{"style", "white-space:nowrap"}], ["Ball State Cardinals"]},
    {"td", [], ["476 "]}, {"td", [], ["\n            51% \n          "]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress wd_progress"}],
       [{"div",
         [{"style", "width:  51%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}, {"td", [], ["52 "]},
    {"td", [], ["\n            51% \n          "]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress wd_progress"}],
       [{"div",
         [{"style", "width:  51%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}, {"td", [], ["U 170 "]},
    {"td", [], ["\n            33% \n          "]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress grey wd_progress"}],
       [{"div",
         [{"style", "width:  33%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}]},
  {"tr", [{"class", "striped"}],
   [{"td", [], ["\n                      7:00pm                  "]},
    {"td", [], ["869"]},
    {"td", [{"style", "white-space:nowrap"}], ["Dayton Flyers "]},
    {"td", [], ["934 "]},
    {"td", [], ["\n                        54%          "]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress wd_progress"}],
       [{"div",
         [{"style", "width:  54%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}, {"td", [], ["111 "]},
    {"td", [], ["\n            43%          "]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress grey wd_progress"}],
       [{"div",
         [{"style", "width:  43%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}, {"td", [], ["O 361 "]},
    {"td", [], [{"font", [{"color", "green"}], ["66%"]}]},
    {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
     [{"div", [{"class", "progress wd_progress"}],
       [{"div",
         [{"style", "width:  66%;"},
          {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
         []}]}]}]}]
  end

  def wunder_row2 do
    {"tr", [{"class", "striped"}],
  [{"td", [],
    [{"a",
      [{"href", "/consensus/viewScoreOdds/event_id/429853.html?width=610"},
       {"name",
        "Dayton Flyers  vs. Rhode Island Rams - Friday February 10, 2017 7:00 pm"},
       {"class", "jTip hidden-xs"}, {"id", "429853"}], ["score »"]},
     {"a",
      [{"href", "/consensus/viewScoreOdds/event_id/429853.html"},
       {"name",
        "Dayton Flyers  vs. Rhode Island Rams - Friday February 10, 2017 7:00 pm"},
       {"class", "visible-xs"}, {"id", "429853"}], ["score »"]}]},
   {"td", [], ["870"]},
   {"td", [{"style", "white-space:nowrap"}], ["Rhode Island Rams"]},
   {"td", [], ["811 "]}, {"td", [], ["\n            46% \n          "]},
   {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
    [{"div", [{"class", "progress grey wd_progress"}],
      [{"div",
        [{"style", "width:  46%;"},
         {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
        []}]}]}, {"td", [], ["148 "]},
   {"td", [], ["\n            57% \n          "]},
   {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
    [{"div", [{"class", "progress wd_progress"}],
      [{"div",
        [{"style", "width:  57%;"},
         {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
        []}]}]}, {"td", [], ["U 185 "]},
   {"td", [], ["\n            34% \n          "]},
   {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
    [{"div", [{"class", "progress grey wd_progress"}],
      [{"div",
        [{"style", "width:  34%;"},
         {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
        []}]}]}]}
  end
end

ExUnit.start

Ecto.Adapters.SQL.Sandbox.mode(TheSpread.Repo, :manual)
