defmodule TheSpread.ExampleRequest do
  # Sport: ncaa_basketball
  # Date: 2017-02-10
  def massey_row1 do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus1 tr0"}, {"data-idx", "3"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531525"}], ["Fri 02.10"]},
     {"div", [{"class", "detail red"}],
      [{"a",
        [{"href",
          "http://www.google.com/cse?cx=partner-pub-0379030414683754:9954400133&ie=UTF-8&q=Dayton Flyers 75 Rhode Island Rams 74 box score&sa=Search&ref=#gsc.tab=0&gsc.q=Dayton Flyers 75 Rhode Island Rams 74 box score&gsc.page=1"}],
        ["FINAL"]}]}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=2085"}], ["Dayton"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=6516"}], ["@ Rhode Island"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 32 (19-5)", {"div", [{"class", "undefined"}], ["# 56 (16-8)"]}]},
   {"td", [{"class", "fscore greybg cWin"}],
    ["75", {"div", [{"class", "undefined white"}], ["74"]}]},
   {"td", [{"class", "fpred white"}],
    ["67", {"div", [{"class", "undefined cWin"}], ["68"]}]},
   {"td", [{"class", "fpred white"}],
    ["48 %", {"div", [{"class", "undefined cWin"}], ["52 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltred visHidden"}], ["4.0"]},
     {"div", [{"class", " ltgreen"}], ["-1.5"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["135.5", {"div", [{"class", "ltred visHidden"}], ["138.5"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end

  def massey_row2 do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus1 tr1"}, {"data-idx", "4"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531526"}], ["Fri 02.10"]},
     {"div", [{"class", "detail red"}],
      [{"a",
        [{"href",
          "http://www.google.com/cse?cx=partner-pub-0379030414683754:9954400133&ie=UTF-8&q=Oakland Golden Grizzlies 89 Detroit Titans 80 box score&sa=Search&ref=#gsc.tab=0&gsc.q=Oakland Golden Grizzlies 89 Detroit Titans 80 box score&gsc.page=1"}],
        ["FINAL"]}]}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=5783"}], ["Oakland"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=2176"}], ["@ Detroit"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 117 (19-7)", {"div", [{"class", "undefined"}], ["# 295 (6-19)"]}]},
   {"td", [{"class", "fscore greybg cWin"}],
    ["89", {"div", [{"class", "undefined white"}], ["80"]}]},
   {"td", [{"class", "fpred cWin"}],
    ["85", {"div", [{"class", "undefined white"}], ["76"]}]},
   {"td", [{"class", "fpred cWin"}],
    ["79 %", {"div", [{"class", "undefined white"}], ["21 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltgreen"}], ["-8.5"]},
     {"div", [{"class", "ltred visHidden"}], ["7.5"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["161.5", {"div", [{"class", "ltred visHidden"}], ["163.5"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end

  def massey_row3 do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus1 tr0"}, {"data-idx", "2"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531528"}], ["Fri 02.10"]},
     {"div", [{"class", "detail red"}],
      [{"a",
        [{"href",
          "http://www.google.com/cse?cx=partner-pub-0379030414683754:9954400133&ie=UTF-8&q=Dartmouth Big Green 64 Yale Bulldogs 73 box score&sa=Search&ref=#gsc.tab=0&gsc.q=Dartmouth Big Green 64 Yale Bulldogs 73 box score&gsc.page=1"}],
        ["FINAL"]}]}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=2052"}], ["Dartmouth"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=9177"}], ["@ Yale"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 318 (4-16)", {"div", [{"class", "undefined"}], ["# 105 (14-6)"]}]},
   {"td", [{"class", "fscore greybg white"}],
    ["64", {"div", [{"class", "undefined cWin"}], ["73"]}]},
   {"td", [{"class", "fpred white"}],
    ["61", {"div", [{"class", "undefined cWin"}], ["78"]}]},
   {"td", [{"class", "fpred white"}],
    ["6 %", {"div", [{"class", "undefined cWin"}], ["94 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltred visHidden"}], ["15.0"]},
     {"div", [{"class", " ltgreen"}], ["-16.5"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["140.5", {"div", [{"class", "ltred visHidden"}], ["138.5"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end

  def massey_row4 do
    {"tr", [{"class", "bodyrow rcCB:NCAA I gstatus1 tr1"}, {"data-idx", "1"}],
  [{"td", [{"class", "fdate sorted"}],
    [{"a", [{"href", "game.php?gid=737531524"}], ["Fri 02.10"]},
     {"div", [{"class", "detail red"}],
      [{"a",
        [{"href",
          "http://www.google.com/cse?cx=partner-pub-0379030414683754:9954400133&ie=UTF-8&q=Cornell Big Red 60 Princeton Tigers 69 box score&sa=Search&ref=#gsc.tab=0&gsc.q=Cornell Big Red 60 Princeton Tigers 69 box score&gsc.page=1"}],
        ["FINAL"]}]}]},
   {"td", [{"class", "fteam tan"}],
    [{"a", [{"href", "team.php?s=292154&t=1910"}], ["Cornell"]},
     {"div", [{"class", "undefined"}],
      [{"a", [{"href", "team.php?s=292154&t=6339"}], ["@ Princeton"]}]}]},
   {"td", [{"class", "frankrec burly"}],
    ["# 291 (6-16)", {"div", [{"class", "undefined"}], ["# 86 (14-6)"]}]},
   {"td", [{"class", "fscore greybg white"}],
    ["60", {"div", [{"class", "undefined cWin"}], ["69"]}]},
   {"td", [{"class", "fpred white"}],
    ["63", {"div", [{"class", "undefined cWin"}], ["77"]}]},
   {"td", [{"class", "fpred white"}],
    ["9 %", {"div", [{"class", "undefined cWin"}], ["91 %"]}]},
   {"td", [{"class", "fscore"}],
    [{"div", [{"class", "ltred visHidden"}], ["16.0"]},
     {"div", [{"class", " ltgreen"}], ["-14.5"]}]},
   {"td", [{"class", "fscore ltgreen"}],
    ["139.5", {"div", [{"class", "ltred visHidden"}], ["140.0"]}]},
   {"td", [{"class", "fdummy"}], []}]}
  end
end

ExUnit.start

Ecto.Adapters.SQL.Sandbox.mode(TheSpread.Repo, :manual)
