teams = %{
"Gonzaga": "Gonzaga Bulldogs",
"Villanova": "Villanova Wildcats",
"Kansas": "Kansas Jayhawks",
"Baylor": "Baylor Bears",
"Wisconsin": "Wisconsin Badgers",
"Arizona": "Arizona Wildcats",
"Virginia": "Virginia Cavaliers",
"Louisville": "Louisville Cardinals",
"Florida": "Florida Gators",
"Kentucky": "Kentucky Wildcats",
"UCLA": "UCLA Bruins",
"West Virginia": "West Virginia Mountaineers",
"Cincinnati": "Cincinnati Bearcats",
"North Carolina": "North Carolina Tar Heels",
"Oregon": "Oregon Ducks",
"Duke": "Duke Blue Devils",
"Purdue": "Purdue Boilermakers",
"Florida St": "Florida State Seminoles",
"Creighton": "Creighton Blue Jays",
"SMU": "SMU Mustangs",
"St Mary's CA": "Saint Mary's CA Gaels",
"Maryland": "Maryland Terrapins",
"Notre Dame": "Notre Dame Fighting Irish",
"South Carolina": "South Carolina Gamecocks",
"Butler": "",
"Oklahoma St": "Oklahoma State Cowboys",
"Xavier": "Xavier Musketeers",
"Wichita St": "Wichita State Shockers",
"Kansas St": "Kansas State Wildcats",
"Iowa St": "Iowa State Cyclones",
"Northwestern": "Northwestern Wildcats",
"Dayton": "Dayton Flyers",
"Minnesota": "Minnesota Golden Gophers",
"USC": "USC Trojans",
"Miami FL": "Miami Hurricanes",
"TCU": "TCU Horned Frogs",
"California": "California Golden Bears",
"VA Commonwealth": "",
"Virginia Tech": "Virginia Tech Hokies",
"Illinois St": "Illinois State Redbirds",
"Tennessee": "Tennessee Volunteers",
"Wake Forest": "Wake Forest Deacons",
"Clemson": "Clemson Tigers",
"Arkansas": "Arkansas Razorbacks",
"Georgia": "Georgia Bulldogs",
"Michigan St": "Michigan State Spartans",
"Seton Hall": "Seton Hall Pirates",
"Marquette": "Marquette Golden Eagles",
"Syracuse": "Syracuse Orange",
"MTSU": "MTSU Blue Raiders",
"Texas Tech": "Texas Tech Red Raiders",
"Michigan": "Michigan Wolverines",
"Georgetown": "Georgetown Hoyas",
"Rhode Island": "Rhode Island Rams",
"Mississippi": "Mississippi Rebels",
"Indiana": "Indiana Hoosiers",
"Georgia Tech": "Ga Tech Yellow Jackets",
"Houston": "Houston Cougars",
"Alabama": "Alabama Crimson Tide",
"Pittsburgh": "Pittsburgh Panthers",
"Vermont": "",
"Auburn": "Auburn Tigers",
"Providence": "Providence Friars",
"Utah": "Utah Utes",
"UNC Wilmington": "NC Wilmington Seahawks",
"Akron": "Akron Zips",
"Nevada": "Nevada Wolf Pack",
"Vanderbilt": "Vanderbilt Commodores",
"Ohio St": "Ohio State Buckeyes",
"Penn St": "Penn State Nittany Lions",
"Texas A&M": "Texas A&M Aggies",
"Belmont": "Belmont Bruins",
"Valparaiso": "Valparaiso Crusaders",
"Memphis": "Memphis Tigers",
"Illinois": "Illinois Fighting Illini",
"Monmouth NJ": "Monmouth Hawks",
"UT Arlington": "Texas Arlington Mavericks",
"Boise St": "Boise State Broncos",
"New Mexico St": "",
"ETSU": "Tennessee State Tigers",
"Richmond": "Richmond Spiders",
"Iowa": "Iowa Hawkeyes",
"Princeton": "Princeton Tigers",
"Mississippi St": "Mississippi State Bulldogs",
"UNC Asheville": "",
"Chattanooga": "UT Chattanooga Moccasins",
"Bucknell": "Bucknell Bison",
"Colorado": "Colorado Buffaloes",
"Arkansas St": "Arkansas St. Red Wolves",
"Col Charleston": "Charleston Cougars",
"NC State": "NC State Wolfpack",
"Nebraska": "Nebraska Cornhuskers",
"Texas": "Texas Longhorns",
"George Mason": "George Mason Patriots",
"BYU": "BYU Cougars",
"Winthrop": "",
"Oklahoma": "Oklahoma Sooners",
"St John's": "St. John's Red Storm",
"Colorado St": "Colorado State Rams",
"Stanford": "Stanford Cardinal",
"St Bonaventure": "St. Bonaventure Bonnies",
"San Francisco": "San Francisco Dons",
"Temple": "Temple Owls",
"La Salle": "La Salle Explorers",
"Furman": "Furman Paladins",
"Connecticut": "Connecticut Huskies",
"New Mexico": "New Mexico Lobos",
"FL Gulf Coast": "",
"UCF": "Central Florida Knights",
"Davidson": "Davidson Wildcats",
"CS Bakersfield": "",
"Harvard": "Harvard Crimson",
"UNC Greensboro": "UNC Greensboro Spartans",
"San Diego St": "SD State Jack Rabbits",
"Georgia St": "Georgia State Panthers",
"Arizona St": "Arizona State Sun Devils",
"Yale": "Yale Bulldogs",
"Oakland": "Oakland Golden Grizzlies",
"G Washington": "G.Washington Colonials",
"N Dakota St": "N. Dakota Fighting Hawks",
"Louisiana Tech": "Louisiana Tech Bulldogs",
"Rutgers": "Rutgers Scarlet Knights",
"Tulsa": "Tulsa Golden Hurricane",
"Ohio": "Ohio Bobcats",
"Santa Clara": "Santa Clara Broncos",
"Towson": "Towson State Tigers",
"Loyola-Chicago": "Loyola Chicago Ramblers",
"Old Dominion": "Old Dominion Monarchs",
"Massachusetts": "Massachusetts Minutemen",
"South Dakota": "South Dakota Coyotes",
"Iona": "Iona Gaels",
"Northern Iowa": "Northern Iowa Panthers",
"Ga": "",
"Lehigh": "",
"Wyoming": "Wyoming Cowboys",
"Washington St": "Washington State Cougars",
"Ga Southern": "Georgia Southern Eagles",
"Rice": "Rice Owls",
"Elon": "Elon College Phoenix",
"San Jose St": "San Jose State Spartans",
"N Kentucky": "Northern Kentucky Norse",
"Buffalo": "Buffalo Bulls",
"Wright St": "Wright State Raiders",
"E Washington": "E. Washington Eagles",
"LSU": "LSU Tigers",
"Weber St": "Weber State Wildcats",
"Fresno St": "Fresno State Bulldogs",
"Lipscomb": "",
"Denver": "Denver University Pioneers",
"William & Mary": "William & Mary Tribe",
"St Joseph's PA": "St. Joseph's Hawks",
"IPFW": "IPFW Mastadons",
"Missouri St": "Mississippi State Bulldogs",
"C Michigan": "C. Michigan Chippewas",
"NC Central": "",
"ern": "",
"Albany NY": "",
"WI Green Bay": "WI-Green Bay Phoenix",
"TN Martin": "Tenn Martin Skyhawks",
"Canisius": "Canisius Golden Griffins",
"S Illinois": "Southern Illinois Salukis",
"Stony Brook": "",
"Liberty": "",
"Grand Canyon": "",
"Loy Marymount": "Loyola Marymount Lions",
"Toledo": "Toledo Rockets",
"Samford": "Samford Bulldogs",
"St Peter's": "Saint Peter's Peacocks",
"Tennessee St": "Tennessee State Tigers",
"ULL": "",
"UAB": "UAB Blazers",
"Boston Univ": "Boston U Terriers",
"Marshall": "Marshall Thundering Herd",
"Boston College": "",
"Morehead St": "Morehead State Eagles",
"Ball St": "Ball State Cardinals",
"Jacksonville St": "Jacksonville St. Gamecocks",
"Utah St": "Utah State Aggies",
"Navy": "",
"North Dakota": "North Dakota State Bison",
"UC Irvine": "Cal Irvine Anteaters",
"Wofford": "Wofford Terriers",
"Evansville": "Evansville Aces",
"NE Omaha": "Nebraska Omaha Mavericks",
"E Michigan": "Eastern Michigan Eagles",
"Siena": "Siena Saints",
"UMBC": "",
"Coastal Car": "C. Carolina Chanticleers",
"Troy": "Troy Trojans",
"New Orleans": "",
"UC Davis": "California Davis Aggies",
"Washington": "Washington Huskies",
"Sam Houston St": "",
"TX": "TX San Antonio Roadrunners",
"Mercer": "Mercer Bears",
"Texas St": "Texas State Bobcats",
"SC Upstate": "",
"Montana": "Montana Grizzlies",
"Kent": "",
"New Hampshire": "",
"Fordham": "Fordham Rams",
"N Illinois": "Northern Illinois Huskies",
"Missouri": "Missouri Tigers",
"Missouri KC": "",
"Indiana St": "Indiana St. Sycamores",
"Mt St Mary's": "Mt. St. Mary's Mountaineers",
"Hofstra": "Hofstra Pride",
"Fairfield": "Fairfield Stags",
"Penn": "Pennsylvania Quakers",
"Murray St": "Murray State Racers",
"South Alabama": "South Alabama Jaguars",
"Idaho": "Idaho Vandals",
"Rider": "Rider Broncs",
"Gardner Webb": "",
"Loyola MD": "",
"DePaul": "Depaul Blue Demons",
"St Louis": "Saint Louis Billikens",
"W Michigan": "Western Michigan Broncos",
"East Carolina": "East Carolina Pirates",
"S Dakota St": "",
"Bowling Green": "Bowling Green Falcons",
"San Diego": "San Diego Toreros",
"TAM C. Christi": "",
"WKU": "W. Kentucky Hilltoppers",
"Columbia": "Columbia Lions",
"Holy Cross": "",
"E Illinois": "Eastern Illinois Panthers",
"Duquesne": "Duquesne Dukes",
"UNLV": "UNLV Runnin' Rebels",
"IUPUI": "IUPUI Jaguars",
"High Point": "",
"IL Chicago": "Illinois Chicago Flames",
"Ark Little Rock": "",
"Charlotte": "NC Charlotte 49ers",
"Long Beach St": "Long Beach State 49ers",
"Utah Valley": "",
"Pepperdine": "Pepperdine Waves",
"Bradley": "Bradley Braves",
"Radford": "",
"Air Force": "Air Force Falcons",
"Montana St": "Montana State Bobcats",
"Quinnipiac": "Quinnipiac Bobcats",
"Long Island": "",
"Portland": "Portland Pilots",
"SF Austin": "",
"Houston Bap": "",
"Portland StB": "Portland State Vikings",
"Lamar": "",
"Oral Roberts": "Oral Roberts Golden Eagles",
"Tennessee Tech": "Tenn Tech Golden Eagles",
"Hawaii": "Hawaii Warriors",
"Delaware": "Delaware Blue Hens",
"Wagner": "Wagner Seahawks",
"Cleveland St": "Cleveland State Vikings",
"Kennesaw": "",
"CS Northridge": "CS Northridge Matadors",
"UTEP": "UTEP Miners",
"SE Missouri St": "SE Missouri St. Redhawks",
"Brown": "Brown Bears",
"Seattle": "",
"UT San Antonio": "TX San Antonio Roadrunners",
"Pacific": "Pacific Tigers",
"Drexel": "Drexel Dragons",
"North Florida": "",
"Colgate": "Colgate Red Raiders",
"Jacksonville": "",
"Robert Morris": "",
"FL Atlantic": "Florida Atlantic Owls",
"F Dickinson": "Farleigh Dickinson Knights",
"Niagara": "Niagara Purple Eagles",
"Campbell": "",
"Appalachian St": "App State Mountaineers",
"Norfolk St": "",
"James Madison": "James Madison Dukes",
"St Francis PA": "",
"SE Louisiana": "",
"Miami OH": "Miami Ohio Redhawks",
"WI Milwaukee": "WI-Milwaukee Panthers",
"Drake": "Drake Bulldogs",
"Manhattan": "Manhattan Jaspers",
"W Illinois": "W. Illinois Leathernecks",
"South Florida": "South Florida Bulls",
"E Kentucky": "E. Kentucky Colonels",
"Youngstown St": "Youngstown State Penguins",
"CS Fullerton": "Cal State Fullerton Titans",
"CS Sacramento": "",
"Sacred Heart": "",
"Binghamton": "",
"Cornell": "Cornell Big Red",
"Austin Peay": "Austin Peay Governors",
"MA Lowell": "",
"UC Riverside": "Cal Riverside Highlanders",
"W Carolina": "W. Carolina Catamounts",
"Cent Arkansas": "",
"Detroit": "Detroit Titans",
"Army": "",
"Hampton": "",
"Alcorn St": "",
"Abilene Chr": "",
"Nicholls St": "",
"Tulane": "Tulane Green Wave",
"UTRGV": "",
"NJIT": "",
"Dartmouth": "Dartmouth Big Green",
"Bryant": "Bryant Bulldogs",
"VMI": "VMI Keydets",
"N Colorado": "Northern Colorado Bears",
"Citadel": "The Citadel Bulldogs",
"Northwestern LA": "",
"ULM": "UL Monroe Warhawks",
"Cal Poly SLO": "Cal Poly SLO Mustangs",
"Incarnate Word": "",
"American Univ": "",
"Oregon St": "Oregon State Beavers",
"Marist": "Marist Red Foxes",
"Morgan St": "Morgan State Bears",
"Northern Arizona": "N. Arizona Lumberjacks",
"Hartford": "",
"Lafayette": "UL Lafayette Ragin Cajuns",
"Savannah St": "",
"Charleston So": "",
"North Texas": "North Texas Mean Green",
"Florida Intl": "Fla Intl Golden Panthers",
"MD E Shore": "",
"Howard": "Howard Bison",
"McNeese St": "",
"Stetson": "",
 "Miss": "Mississippi Rebels",
"Delaware St": "",
"Idaho St": "Idaho State Bengals",
"Prairie View": "",
"Chicago St": "",
 "Univ": "",
"Edwardsville": "SIU Edwardsville Cougars",
"Santa Barbara": "Santa Barbara Gauchos",
"S Carolina St": "",
"Jackson St": "",
"Maine": "",
"Central Conn": "",
"Grambling": "",
"Alabama St": "",
"Longwood": ""}
