{"tr", [{"class", ""}],
 [{"td", [],
   [{"a",
     [{"href", "/consensus/viewScoreOdds/event_id/429862.html?width=610"},
      {"name",
       "Ohio Bobcats vs. Ball State Cardinals - Friday February 10, 2017 6:30 pm"},
      {"class", "jTip hidden-xs"}, {"id", "429862"}], ["score »"]},
    {"a",
     [{"href", "/consensus/viewScoreOdds/event_id/429862.html"},
      {"name",
       "Ohio Bobcats vs. Ball State Cardinals - Friday February 10, 2017 6:30 pm"},
      {"class", "visible-xs"}, {"id", "429862"}], ["score »"]}]},
  {"td", [], ["888"]},
  {"td", [{"style", "white-space:nowrap"}], ["Ball State Cardinals"]},
  {"td", [], ["476 "]}, {"td", [], ["\n            51% \n          "]},
  {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
   [{"div", [{"class", "progress wd_progress"}],
     [{"div",
       [{"style", "width:  51%;"},
        {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
       []}]}]}, {"td", [], ["52 "]},
  {"td", [], ["\n            51% \n          "]},
  {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
   [{"div", [{"class", "progress wd_progress"}],
     [{"div",
       [{"style", "width:  51%;"},
        {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
       []}]}]}, {"td", [], ["U 170 "]},
  {"td", [], ["\n            33% \n          "]},
  {"td", [{"class", "pc_percent_bar"}, {"valign", "middle"}],
   [{"div", [{"class", "progress grey wd_progress"}],
     [{"div",
       [{"style", "width:  33%;"},
        {"class", "progress-bar progress-bar-warning progress-bar-striped"}],
       []}]}]}]}
